sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hatAhkQ13K7qvglpn0J/i2qiLPF1sHBSAuC7H2497fTuHD45J8PTIlHX7tGrou6H19UUdK4vRJW2OR62j5OUFloM1o8D3A+wXSeZT7mnF/IU2+8Egwgucc4b5Kd7vNVIAE6fh+5JFIx0eBwVlX2cXL25Dx8NNoBMcKjMIXVUeIodo8cowCQOgU5di82oCS2J3mHcO7iMuhTcIbAgswLfBFY38M4FvTkcc3rGMY+RKbgBsASDo1f+BW4FZPN5sTwe9TklCNp0bC3QFgipsF52f04aFhfV18IW0J9ifW+0szwt3O8kN8Lggq1kmC1j0u6sGyE0mOzb0lrIYb6ngHq9+DlsBTsId1561qZv01M0W54j1iPxAY1bhN7LIfzcIcdPLeiTrL3BbwU1mhoLEHHDuwZXTv3G0aF5LwhODe1Sm+Z3t91uLy4yMj9Q/OPKDxyf3WF8TpCVZJpFwNubn/cbQ1FKInnj9/SfbSKs0BH0430gOsqEjLuR4C0e+3BSJiBXo3C7ln8DwsxEM3lK4Apuamj9GbMzog7t9MUty9j7hUjcQKYqbs9xnGFH8sUQk4y5wYD8s3Y6eZd1wYO87VerxKs/FJY48N3ru4kNiUV+XVZDM7UKl+99p1LK+6BKMqvt7l/eMkjbdoOrTKWYvrNDt+8hpT3KIWxX6DH4vZ8c5S4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Vera-the-Medium_1843
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy